export const CACHE_TAGS = {
  categories: "categories",
  category: (id: number) => `category-${id}`,
  lessons: "lessons",
  lesson: (id: number) => `lesson-${id}`,
  transcripts: "transcripts",
  transcript: (id: number) => `transcript-${id}`,
  users: "users",
  user: (id: string) => `user-${id}`,
  bookmarks: "transcript-bookmarks",
  learningHistory: "learning-history",
  vocabularyCategories: "vocabulary-categories",
  vocabularyCategory: (id: number) => `vocabulary-category-${id}`,
  vocabularyDecks: "vocabulary-decks",
  vocabularyDeck: (id: number) => `vocabulary-deck-${id}`,
  vocabularyItems: "vocabulary-items",
  vocabularyItem: (id: number) => `vocabulary-item-${id}`,
  shadowingStatus: "shadowing-status",
  dictationStatus: "dictation-status",
  pronunciation: "pronunciation",
  pronunciationProgress: "pronunciation-progress",
  transcriptProgress: "transcript-progress",
  lessonBookmarks: "lesson-bookmarks",
} as const
