// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/sync": {
            "post": {
                "description": "Verify Firebase ID token and create or get user in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sync user with Firebase",
                "parameters": [
                    {
                        "description": "Firebase ID token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_modules_auth_dtos_req.SyncReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_auth_dtos_res_SyncRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "post": {
                "description": "Sign in with email \u0026 password to get a Firebase ID token for use in protected endpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get Firebase ID token",
                "parameters": [
                    {
                        "description": "Email and password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_modules_auth_dtos_req.GetTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_auth_dtos_res_TokenRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/bookmarks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the authenticated user's bookmarks with lesson details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "List user bookmarks",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_bookmark_dtos_res_BookmarkRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/bookmarks/{lessonId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a lesson to user's bookmarks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Add bookmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lesson ID",
                        "name": "lessonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a lesson from user's bookmarks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookmarks"
                ],
                "summary": "Remove bookmark",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lesson ID",
                        "name": "lessonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Get all categories with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "List categories",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_category_dtos_res_CategoryRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/learning-history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the authenticated user's learning history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning-history"
                ],
                "summary": "List learning history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Record or update a user's learning progress for a lesson",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning-history"
                ],
                "summary": "Record learning progress",
                "parameters": [
                    {
                        "description": "Record request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_modules_learning_history_dtos_req.RecordHistoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/learning-history/{lessonId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the user's learning history for a specific lesson",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "learning-history"
                ],
                "summary": "Get history for a lesson",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lesson ID",
                        "name": "lessonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/lessons": {
            "get": {
                "description": "Get all lessons with optional filters and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lessons"
                ],
                "summary": "List lessons",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by category ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by level (beginner/intermediate/advanced)",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/lessons/{lessonId}": {
            "get": {
                "description": "Get a lesson by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lessons"
                ],
                "summary": "Get a lesson",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lesson ID",
                        "name": "lessonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/lessons/{lessonId}/transcripts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all transcripts for a lesson sorted by sequence",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcripts"
                ],
                "summary": "Get lesson transcripts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lesson ID",
                        "name": "lessonId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-array_go-cover-parroto_internal_modules_transcript_dtos_res_TranscriptRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the profile of the currently authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_user_dtos_res_UserRes"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-cover-parroto_internal_core_response.BaseResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-array_go-cover-parroto_internal_modules_transcript_dtos_res_TranscriptRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-cover-parroto_internal_modules_transcript_dtos_res.TranscriptRes"
                    }
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_bookmark_dtos_res_BookmarkRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_bookmark_dtos_res_BookmarkRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_category_dtos_res_CategoryRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_category_dtos_res_CategoryRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_core_response_PaginatedResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_auth_dtos_res_SyncRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_auth_dtos_res.SyncRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_auth_dtos_res_TokenRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_auth_dtos_res.TokenRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_learning_history_dtos_res.LearningHistoryRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_lesson_dtos_res.LessonRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.BaseResponse-go-cover-parroto_internal_modules_user_dtos_res_UserRes": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_user_dtos_res.UserRes"
                },
                "error": {},
                "meta": {
                    "description": "optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                        }
                    ]
                }
            }
        },
        "go-cover-parroto_internal_core_response.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "description": "SQL-style pagination",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_bookmark_dtos_res_BookmarkRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-cover-parroto_internal_modules_bookmark_dtos_res.BookmarkRes"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                }
            }
        },
        "go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_category_dtos_res_CategoryRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-cover-parroto_internal_modules_category_dtos_res.CategoryRes"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                }
            }
        },
        "go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_learning_history_dtos_res_LearningHistoryRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-cover-parroto_internal_modules_learning_history_dtos_res.LearningHistoryRes"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                }
            }
        },
        "go-cover-parroto_internal_core_response.PaginatedResponse-go-cover-parroto_internal_modules_lesson_dtos_res_LessonRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-cover-parroto_internal_modules_lesson_dtos_res.LessonRes"
                    }
                },
                "meta": {
                    "$ref": "#/definitions/go-cover-parroto_internal_core_response.Meta"
                }
            }
        },
        "go-cover-parroto_internal_modules_auth_dtos_req.GetTokenReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "go-cover-parroto_internal_modules_auth_dtos_req.SyncReq": {
            "type": "object",
            "required": [
                "firebase_token"
            ],
            "properties": {
                "firebase_token": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_auth_dtos_res.SyncRes": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_auth_dtos_res.TokenRes": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "string"
                },
                "id_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_bookmark_dtos_res.BookmarkRes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "lesson": {
                    "$ref": "#/definitions/go-cover-parroto_internal_modules_bookmark_dtos_res.LessonInfo"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "go-cover-parroto_internal_modules_bookmark_dtos_res.LessonInfo": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_category_dtos_res.CategoryRes": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_learning_history_dtos_req.RecordHistoryReq": {
            "type": "object",
            "required": [
                "duration_watched",
                "lesson_id"
            ],
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "duration_watched": {
                    "type": "number",
                    "minimum": 0
                },
                "lesson_id": {
                    "type": "integer"
                }
            }
        },
        "go-cover-parroto_internal_modules_learning_history_dtos_res.LearningHistoryRes": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "duration_watched": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "go-cover-parroto_internal_modules_lesson_dtos_res.LessonRes": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "video_url": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_transcript_dtos_res.TranscriptRes": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "end_timestamp": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "phonetic": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "start_timestamp": {
                    "type": "number"
                },
                "vietnamese": {
                    "type": "string"
                }
            }
        },
        "go-cover-parroto_internal_modules_user_dtos_res.UserRes": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Engflix API",
	Description:      "Engflix - Language Learning Platform API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
