import type { Lesson, Transcript } from "@/types/lessons.models"
import type { Category } from "@/types/categories.models"

export const mockCategories: Category[] = [
  { id: 1, name: "Daily English Conversation" },
  { id: 2, name: "IPA" },
  { id: 3, name: "Movie short clip" },
  { id: 4, name: "US UK songs" },
]

export const mockLessons: Lesson[] = [
  {
    id: 1,
    title: "PRINCESS MONONOKE | Official English Trailer",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68aee50c580865082c766e54/thumbnail-W9K3VuABB_Grrd1oH2vIP.webp.webp",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: 64,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 2,
    title: "Love mom",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6900de79f1a22d0de4fdcb95/thumbnail-6900de79f1a22d0de4fdcb95-1761664633506.jpg",
    videoUrl: "https://youtu.be/_cMxraX_5RE",
    duration: 144,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 3,
    title: "Valentine's Day Story | Culture and History | Stories for Kids",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/698b5b004eac74d613f416bf/thumbnail-698b5b004eac74d613f416bf-1770740480744.jpg",
    videoUrl: "https://www.youtube.com/embed/9bZkp7q19f0",
    duration: 179,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 4,
    title: "A Sweet Welcome",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68cfcd525093af1366bb8c5e/thumbnail-68cfcd525093af1366bb8c5e-1758448978127.jpg",
    videoUrl: "https://youtube.com/watch?v=jNQXAC9IVRw",
    duration: 34,
    level: "beginner",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 5,
    title: "Learn Phonetics (IPA) in under 5 minutes",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6874d2c180def0cd6776f947/thumbnail-mK-yKq65tSGzziWTDc24v.webp",
    videoUrl: "https://www.youtube.com/watch?v=OM7s9KQUjfI",
    duration: 353,
    level: "beginner",
    categoryId: 2,
    createdAt: "",
  },
  {
    id: 6,
    title: "Consonant 20 - /h/",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6874c33d80def0cd6776e27c/thumbnail-ebvYtIywZEfHQOoP76aTx.webp",
    videoUrl: "",
    duration: 518,
    level: "intermediate",
    categoryId: 2,
    createdAt: "",
  },
  {
    id: 7,
    title: "I Want It That Way | Brooklyn Nine-Nine",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6879d802031abd3e6f71e7ae/thumbnail-jjLHbK1F85Ls245-znkcM.webp",
    videoUrl: "",
    duration: 88,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 8,
    title: "Passenger | Let Her Go",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6843c74631a5b5cf1e508887/thumbnail-Zvrb3OX7IMGwkymiFoWs2.webp",
    videoUrl: "",
    duration: 255,
    level: "intermediate",
    categoryId: 4,
    createdAt: "",
  },
  {
    id: 9,
    title: "Cam 20 Test 1 Part 1",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/categories/681dcf7da3294dc1507b4fae/thumbnail-B1JwDEQCa7PhQPsrtz7Ua.webp",
    videoUrl: "",
    duration: 501,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 10,
    title: "KIKI'S DELIVERY SERVICE | Official English Trailer",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/686f7e607c5fd89a7883eec3/thumbnail-J7BQpBD8LCWNgALrJr95C.webp.webp",
    videoUrl: "",
    duration: 50,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 11,
    title: "Backstreet Boys - I Want It That Way",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6894a828e8e8c5631a68ed8b/thumbnail-6894a828e8e8c5631a68ed8b-1754572840141.jpg",
    videoUrl: "",
    duration: 220,
    level: "intermediate",
    categoryId: 4,
    createdAt: "",
  },
  {
    id: 12,
    title: "number one girl - ROSE",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6850f0b22e08b5b47f943c58/thumbnail-W4LOIcOLO3eNdNtwqPABn.webp",
    videoUrl: "",
    duration: 218,
    level: "beginner",
    categoryId: 4,
    createdAt: "",
  },
  {
    id: 13,
    title: "Day By Day - one minute phrase lesson",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/686e8b2aac06354629c608d4/thumbnail-Z_qLDmoHMLyO1bYjwGFGY.webp",
    videoUrl: "",
    duration: 112,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 14,
    title: "A1 English Listening Practice - Supermarket",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68923c5665410b3176ff9eb1/thumbnail-68923c5665410b3176ff9eb1-1754414166562.jpg",
    videoUrl: "",
    duration: 277,
    level: "beginner",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 15,
    title: "What vs Which : English In A Minute",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/686e5aa9ac06354629c5d43e/thumbnail-UNmuZCTDvvhpGW8EseIde.webp",
    videoUrl: "",
    duration: 61,
    level: "beginner",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 16,
    title: "Jack and the beanstalk - Kids Stories",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68e54fc607c875a9a1bf39e7/thumbnail-RT-66NuXWCvWPmRt_lPaE.webp.webp",
    videoUrl: "",
    duration: 205,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 17,
    title: "Weathering With You [Official English Dub Trailer]",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68ab4bdc6e35cd396c8db5a2/thumbnail-68ab4bdc6e35cd396c8db5a2-1756056540264.jpg",
    videoUrl: "",
    duration: 121,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 18,
    title: "English in a Minute: Pack Rat",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/689cb9f8186a4c2f57f75a7f/thumbnail-T77zhafmRAfTkzVee8_Jq.webp.webp",
    videoUrl: "",
    duration: 60,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 19,
    title: "Consonant 21 - /j/",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6874c31480def0cd6776e21b/thumbnail-TSxz4fatuGASo6MPJlTLC.webp",
    videoUrl: "",
    duration: 518,
    level: "intermediate",
    categoryId: 2,
    createdAt: "",
  },
  {
    id: 20,
    title: "The Frightened Lion",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6875f6e103803ebed7e96cb5/thumbnail-NxW3zynG0hEqg9bfuCHJ8.webp",
    videoUrl: "",
    duration: 162,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
]

export const mockTranscripts: Transcript[] = [
  { id: 1, lessonId: 1, sequence: 1, content: "In a world where the forest meets the iron age,", phonetic: "", vietnamese: "", startTimestamp: 0, endTimestamp: 4 },
  { id: 2, lessonId: 1, sequence: 2, content: "a young prince embarks on a journey to find a cure for a curse.", phonetic: "", vietnamese: "", startTimestamp: 4, endTimestamp: 8 },
  { id: 3, lessonId: 1, sequence: 3, content: "He encounters a fierce young woman raised by wolves,", phonetic: "", vietnamese: "", startTimestamp: 8, endTimestamp: 12 },
  { id: 4, lessonId: 1, sequence: 4, content: "who fights to protect the forest and its spirits.", phonetic: "", vietnamese: "", startTimestamp: 12, endTimestamp: 16 },
  { id: 5, lessonId: 1, sequence: 5, content: "Together they must stop the forces of destruction", phonetic: "", vietnamese: "", startTimestamp: 16, endTimestamp: 20 },
  { id: 6, lessonId: 1, sequence: 6, content: "before the balance of nature is lost forever.", phonetic: "", vietnamese: "", startTimestamp: 20, endTimestamp: 24 },
]
