import type { Lesson, Transcript } from "@/types/lessons.models"
import type { Category } from "@/types/categories.models"

export const mockCategories: Category[] = [
  { id: 1, name: "Daily English Conversation" },
  { id: 2, name: "IPA" },
  { id: 3, name: "Movie short clip" },
  { id: 4, name: "US UK songs" },
]

export const mockLessons: Lesson[] = [
  {
    id: 1,
    title: "PRINCESS MONONOKE | Official English Trailer",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68aee50c580865082c766e54/thumbnail-W9K3VuABB_Grrd1oH2vIP.webp.webp",
    videoUrl: "",
    duration: 64,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 2,
    title: "Love mom",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6900de79f1a22d0de4fdcb95/thumbnail-6900de79f1a22d0de4fdcb95-1761664633506.jpg",
    videoUrl: "",
    duration: 144,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 3,
    title: "Valentine's Day Story | Culture and History | Stories for Kids",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/698b5b004eac74d613f416bf/thumbnail-698b5b004eac74d613f416bf-1770740480744.jpg",
    videoUrl: "",
    duration: 179,
    level: "intermediate",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 4,
    title: "A Sweet Welcome",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/68cfcd525093af1366bb8c5e/thumbnail-68cfcd525093af1366bb8c5e-1758448978127.jpg",
    videoUrl: "",
    duration: 34,
    level: "beginner",
    categoryId: 1,
    createdAt: "",
  },
  {
    id: 5,
    title: "Learn Phonetics (IPA) in under 5 minutes",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6874d2c180def0cd6776f947/thumbnail-mK-yKq65tSGzziWTDc24v.webp",
    videoUrl: "",
    duration: 353,
    level: "beginner",
    categoryId: 2,
    createdAt: "",
  },
  {
    id: 6,
    title: "Consonant 20 - /h/",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6874c33d80def0cd6776e27c/thumbnail-ebvYtIywZEfHQOoP76aTx.webp",
    videoUrl: "",
    duration: 518,
    level: "intermediate",
    categoryId: 2,
    createdAt: "",
  },
  {
    id: 7,
    title: "I Want It That Way | Brooklyn Nine-Nine",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6879d802031abd3e6f71e7ae/thumbnail-jjLHbK1F85Ls245-znkcM.webp",
    videoUrl: "",
    duration: 88,
    level: "intermediate",
    categoryId: 3,
    createdAt: "",
  },
  {
    id: 8,
    title: "Passenger | Let Her Go",
    description: "",
    thumbnailUrl: "https://assets.parroto.app/assets/lessons/6843c74631a5b5cf1e508887/thumbnail-Zvrb3OX7IMGwkymiFoWs2.webp",
    videoUrl: "",
    duration: 255,
    level: "intermediate",
    categoryId: 4,
    createdAt: "",
  },
]

export const mockTranscripts: Transcript[] = [
  { id: 1, lessonId: 1, sequence: 1, content: "In a world where the forest meets the iron age,", phonetic: "", vietnamese: "", startTimestamp: 0, endTimestamp: 4 },
  { id: 2, lessonId: 1, sequence: 2, content: "a young prince embarks on a journey to find a cure for a curse.", phonetic: "", vietnamese: "", startTimestamp: 4, endTimestamp: 8 },
  { id: 3, lessonId: 1, sequence: 3, content: "He encounters a fierce young woman raised by wolves,", phonetic: "", vietnamese: "", startTimestamp: 8, endTimestamp: 12 },
  { id: 4, lessonId: 1, sequence: 4, content: "who fights to protect the forest and its spirits.", phonetic: "", vietnamese: "", startTimestamp: 12, endTimestamp: 16 },
  { id: 5, lessonId: 1, sequence: 5, content: "Together they must stop the forces of destruction", phonetic: "", vietnamese: "", startTimestamp: 16, endTimestamp: 20 },
  { id: 6, lessonId: 1, sequence: 6, content: "before the balance of nature is lost forever.", phonetic: "", vietnamese: "", startTimestamp: 20, endTimestamp: 24 },
]
