// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-cover-parroto/internal/controller"
	"go-cover-parroto/internal/repo"
	"go-cover-parroto/internal/service"
)

// Injectors from user.wire.go:

func InitUserRouterHandle() (*controller.UserController, error) {
	iuserRepo := repo.NewUserRepo()
	iUserService := service.NewUserService(iuserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
